#!/bin/bash

mkdir -p app/static/products

cd app/static/products

wget -q "https://cdn.tgdd.vn/Products/Images/42/213031/iphone-12-xanh-duong-new-600x600.jpg" -O iPhone-12-64GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/228744/iphone-12-pro-max-vang-new-600x600-600x600.jpg" -O iPhone-12-Pro-Max-512GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/228739/iphone-12-pro-xanh-duong-new-600x600-600x600.jpg" -O iPhone-12-Pro-512GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/228743/iphone-12-pro-max-vang-new-600x600-600x600.jpg" -O iPhone-12-Pro-Max-256GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/228738/iphone-12-pro-xam-new-600x600-600x600.jpg" -O iPhone-12-Pro-256GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-xanh-duong-new-600x600-600x600.jpg" -O iPhone-12-Pro-Max-128GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/213032/iphone-12-pro-bac-new-600x600-600x600.jpg" -O iPhone-12-Pro-128GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/228737/iphone-12-white-600x600.jpg" -O iPhone-12-256GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/228736/iphone-12-white-600x600.jpg" -O iPhone-12-128GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/228742/iphone-23-mini-den-new-600x600-600x600.jpg" -O iPhone-12-mini-256GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/210648/iphone-11-den-600x600.jpg" -O iPhone-11-256GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/210644/iphone-11-xanhla-600x600.jpg" -O iPhone-11-128GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/228741/iphone-mini-do-new-600x600-600x600.jpg" -O iPhone-12-mini-128GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/225380/iphone-mini-do-new-600x600-600x600.jpg" -O iPhone-12-mini-64GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/153856/iphone-xi-do-600x600.jpg" -O iPhone-11-64GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/191483/iphone-xr-128gb-400x400.jpg" -O iPhone-XR-128GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/222631/iphone-se-128gb-2020-den-600x600.jpg" -O iPhone-SE-256GB-2020.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/190325/iphone-xr-hopmoi-den-600x600-2-600x600.jpg" -O iPhone-XR-64GB.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/222629/iphone-se-128gb-2020-trang-600x600.jpg" -O iPhone-SE-128GB-2020.jpg
wget -q "https://cdn.tgdd.vn/Products/Images/42/230412/iphone-se-2020-trang-600x600-600x600.jpg" -O iPhone-SE-128GB-2020-Hop-Moi.jpg

exit
